name: e2e test
on: [push, pull_request]

jobs:
  e2e:
    name: e2e test
    runs-on: ubuntu-20.04
    steps:
      - name: checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Install Wget
        run: |
          sudo apt update
          sudo apt -y install wget
      - run: wget -c https://github.com/KusionStack/KCLVM/releases/download/v0.4.6/kclvm-v0.4.6-linux-amd64.tar.gz -qO - | tar xz -C ./
  
      - name: run e2e
        run: |
          export PATH=$PATH:$(pwd)/kclvm/bin
          kclvm_cli version 
          make e2e
